{
  "openapi": "3.0.0",
  "info": {
    "version": "0.0.2",
    "title": "Lux CRM Core",
    "description": "Api documentation for Lux CRM Back End Core."
  },
  "schemes": ["https"],
  "servers": [
    {
      "description": "Localhost Development API.",
      "url": "http://localhost:3000/V1"
    }
  ],
  "components": {
    "securitySchemes": {
      "Token": {
        "type": "apiKey",
        "in": "header",
        "name": "Authentication"
      },
      "FingerprintID": {
        "type": "apiKey",
        "in": "header",
        "name": "Fingerprint"
      },
      "SessionID": {
        "type": "apiKey",
        "in": "header",
        "name": "Session"
      }
    },
    "schemas": {
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "passwd": {
            "type": "string"
          }
        }
      },
      "RefreshToken": {
        "type": "object",
        "properties": {
          "refreshToken": {
            "type": "string"
          }
        }
      },
      "SessionId": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "example": "usuariodeteste@gmail.com"
          },
          "passwd": {
            "type": "string",
            "example": "SenhaDeTeste@123"
          },
          "name": {
            "type": "string",
            "example": "User"
          },
          "lastName": {
            "type": "string",
            "example": "de Teste"
          },
          "phone": {
            "type": "string",
            "example": "(11) 9 9171-8696"
          }
        }
      },
      "PatchUser": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "required": false,
            "format": "email",
            "example": "usuariodeteste@gmail.com"
          },
          "passwd": {
            "required": false,
            "type": "string",
            "example": "SenhaDeTeste@123"
          },
          "name": {
            "required": false,
            "type": "string",
            "example": "User"
          },
          "lastName": {
            "required": false,
            "type": "string",
            "example": "de Teste"
          },
          "phone": {
            "required": false,
            "type": "string",
            "example": "(11) 9 9171-8696"
          }
        }
      }
    }
  },
  "security": [
    {
      "Token": []
    },
    {
      "FingerprintID": []
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "summary": "Fazer login.",
        "tags": ["Authentication"],
        "description": "Faça seu login e receba de volta um token e um refresh token.",
        "security": [
          {
            "FingerprintID": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "Autenticando com email e senha.": {
                  "value": {
                    "email": "usuariodeteste@gmail.com",
                    "passwd": "SenhaDeTeste@123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Autenticado com sucesso."
                    },
                    "token": {
                      "type": "string",
                      "example": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjExZjdkYmRiMjJmNmM3NWFlZTJkOSIsInNlc3Npb25JZCI6IjY3ZjEyNDU5NDk3ZDJlMjIyZTFiZjRkNiIsInR5cGUiOiJUb2tlbiIsImlhdCI6MTc0Mzg3OTM2MiwiZXhwIjoxNzQ0NDc5MzYyfQ.P69JGGjp0CyVbkS-vzd4HPwNXrHlLrBXhqkNpsv6L90"
                    },
                    "refreshToken": {
                      "type": "string",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjExZjdkYmRiMjJmNmM3NWFlZTJkOSIsInNlc3Npb25JZCI6IjY3ZjEyNDU5NDk3ZDJlMjIyZTFiZjRkNiIsInR5cGUiOiJSZWZyZXNoVG9rZW4iLCJpYXQiOjE3NDM4NzkzNjIsImV4cCI6MTkxNjY3OTM2Mn0.PgbPFkM8hhizs3LRpIFyBaDNBs5TvxBQ_uLPNpuX0Lw"
                    },
                    "sessionId": {
                      "type": "string",
                      "example": "67f50cfe9e1723f372bae825"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": "67f11f7dbdb22f6c75aee2d9",
                        "createdAt": "2025-04-05T12:18:05.112Z",
                        "updatedAt": "2025-04-05T12:18:05.112Z",
                        "active": true,
                        "email": "joseaugustholi@gmail.com",
                        "emailVerified": false,
                        "emailNotification": true,
                        "agree": true,
                        "name": "José",
                        "lastName": "Augustho",
                        "passwd": "********************************",
                        "phone": "(34) 99171-8593",
                        "role": "USER"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/refresh": {
      "post": {
        "summary": "Atualizar token para manter a sessão ativa.",
        "tags": ["Authentication"],
        "description": "Envie o refreshToken e receba um token e um refreshToken novos.",
        "security": [
          {
            "FingerprintID": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshToken"
              },
              "examples": {
                "Atualizando token e refreshToken": {
                  "value": {
                    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjEyNmYwMzFlYjU3NjIzYmZkOTZlYiIsInNlc3Npb25JZCI6IjY3ZjEyY2QwM2FjNmNiYzU3OTczNzA3MSIsImlhdCI6MTc0Mzg1ODg5NiwiZXhwIjoxOTE2NjU4ODk2fQ.YRDejsPts2C68zr7xXa_TRsmliDoztKeUGu6DwwCXsQ"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Autenticado com sucesso."
                    },
                    "token": {
                      "type": "string",
                      "example": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjExZjdkYmRiMjJmNmM3NWFlZTJkOSIsInNlc3Npb25JZCI6IjY3ZjEyNDU5NDk3ZDJlMjIyZTFiZjRkNiIsInR5cGUiOiJUb2tlbiIsImlhdCI6MTc0Mzg3OTM2MiwiZXhwIjoxNzQ0NDc5MzYyfQ.P69JGGjp0CyVbkS-vzd4HPwNXrHlLrBXhqkNpsv6L90"
                    },
                    "refreshToken": {
                      "type": "string",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjExZjdkYmRiMjJmNmM3NWFlZTJkOSIsInNlc3Npb25JZCI6IjY3ZjEyNDU5NDk3ZDJlMjIyZTFiZjRkNiIsInR5cGUiOiJSZWZyZXNoVG9rZW4iLCJpYXQiOjE3NDM4NzkzNjIsImV4cCI6MTkxNjY3OTM2Mn0.PgbPFkM8hhizs3LRpIFyBaDNBs5TvxBQ_uLPNpuX0Lw"
                    },
                    "sessionId": {
                      "type": "string",
                      "example": "67f50cfe9e1723f372bae825"
                    },
                    "data": {
                      "type": "object",
                      "format": "email",
                      "example": {
                        "id": "67f11f7dbdb22f6c75aee2d9",
                        "createdAt": "2025-04-05T12:18:05.112Z",
                        "updatedAt": "2025-04-05T12:18:05.112Z",
                        "active": true,
                        "email": "joseaugustholi@gmail.com",
                        "emailVerified": false,
                        "emailNotification": true,
                        "agree": true,
                        "name": "José",
                        "lastName": "Augustho",
                        "passwd": "********************************",
                        "phone": "(34) 99171-8593",
                        "role": "USER"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Cria um novo usuário.",
        "tags": ["User"],
        "description": "Cria um novo usuário.",
        "security": [
          {
            "FingerprintID": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Usuário criado com sucesso."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Retorna os dados usuário autenticado.",
        "tags": ["User"],
        "description": "Retorna o usuário autenticado com base no header Authorization.",
        "security": [
          {
            "FingerprintID": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Usuário encontrado."
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "data": {
                          "id": "67fecf502cdddf231a5db1e5",
                          "createdAt": "2025-04-15T21:27:12.086Z",
                          "updatedAt": "2025-04-15T21:27:12.086Z",
                          "active": true,
                          "email": "usuáriodeteste@gmail.com",
                          "emailNotification": true,
                          "agree": true,
                          "name": "José",
                          "lastName": "Augustho",
                          "passwd": "*************************************",
                          "phone": "(34) 99171-8593",
                          "authorizedSessionsId": [
                            "67feca2e34e83e5d55527cc9",
                            "6800351527e549a02866a56a",
                            "68012bbcd252f937ea1f6676"
                          ],
                          "role": "USER"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError | TokenError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Atualiza o usuário autenticado.",
        "description": "Atualiza o usuário autenticado, não pode ser utilizada.",
        "tags": ["User"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PatchUser"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Usuário atualizado com sucesso."
                    },
                    "info": {
                      "type": "object",
                      "properties": {
                        "info": {
                          "type": "number",
                          "example": 1
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/support/user": {
      "patch": {
        "summary": "Retorna um usuário.",
        "description": "Retorna o usuário à qual pertence o ID específicado.",
        "tags": ["User", "Support"],
        "security": [
          {
            "FingerprintID": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PatchUser"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Usuário atualizado com sucesso."
                    },
                    "info": {
                      "type": "object",
                      "properties": {
                        "info": {
                          "type": "number",
                          "example": 1
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Retorna os dados usuário autenticado.",
        "tags": ["User", "Support", "Admin"],
        "description": "Retorna o usuário autenticado com base no header Authorization.",
        "security": [
          {
            "FingerprintID": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Usuário encontrado."
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "data": {
                          "id": "67fecf502cdddf231a5db1e5",
                          "createdAt": "2025-04-15T21:27:12.086Z",
                          "updatedAt": "2025-04-15T21:27:12.086Z",
                          "active": true,
                          "email": "usuáriodeteste@gmail.com",
                          "emailNotification": true,
                          "agree": true,
                          "name": "José",
                          "lastName": "Augustho",
                          "passwd": "*************************************",
                          "phone": "(34) 99171-8593",
                          "authorizedSessionsId": [
                            "67feca2e34e83e5d55527cc9",
                            "6800351527e549a02866a56a",
                            "68012bbcd252f937ea1f6676"
                          ],
                          "role": "USER"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError | TokenError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/support/users": {
      "get": {
        "summary": "Retorna todos os usuários. (Somente admins)",
        "tags": ["Support", "User"],
        "description": "Retorna todos os usuários com base na paginação e filtros de busca.",
        "parameters": [
          {
            "name": "skip",
            "description": "Pular os X primeiros usuários. (paginação)",
            "in": "query",
            "required": false,
            "schema": {
              "type": "number",
              "example": "0"
            }
          },
          {
            "name": "take",
            "description": "Mostrar os X primeiros usuários. (paginação)",
            "in": "query",
            "required": false,
            "schema": {
              "type": "number",
              "example": "100"
            }
          },
          {
            "name": "search",
            "description": "Pesquisa os usuários que incluirem o parametro search. (Não é case sensitive)",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "example": "José"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de usuários encontrados",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "info": {
                      "type": "object",
                      "properties": {
                        "lenght": 3,
                        "showing": 100,
                        "skipped": 0
                      }
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string",
                            "example": "67fecf502cdddf231abdb1e5"
                          },
                          "createdAt": {
                            "type": "string",
                            "format": "date-time",
                            "example": "2025-04-15T21:27:12.086Z"
                          },
                          "updatedAt": {
                            "type": "string",
                            "format": "date-time",
                            "example": "2025-04-15T21:27:12.086Z"
                          },
                          "active": { "type": "boolean", "example": true },
                          "email": {
                            "type": "string",
                            "example": "joseaugustholi@gmail.com"
                          },
                          "emailNotification": {
                            "type": "boolean",
                            "example": true
                          },
                          "agree": { "type": "boolean", "example": true },
                          "name": { "type": "string", "example": "José" },
                          "lastName": {
                            "type": "string",
                            "example": "Augustho"
                          },
                          "passwd": {
                            "type": "string",
                            "example": "*************************************"
                          },
                          "phone": {
                            "type": "string",
                            "example": "(34) 99171-8593"
                          },
                          "authorizedSessionsId": {
                            "type": "array",
                            "items": { "type": "string" },
                            "example": [
                              "67feca2e34e83ead55527cc9",
                              "6800351527e549a02865a56a",
                              "68012bbcd252f937ea1f5676"
                            ]
                          },
                          "role": { "type": "string", "example": "USER" }
                        }
                      }
                    }
                  },
                  "example": {
                    "status": "Ok",
                    "message": "Usuários encontrados.",
                    "info": {
                      "lenght": 3,
                      "showing": 100,
                      "skipped": 0
                    },
                    "data": [
                      {
                        "id": "67fecf502csddf231abdb1e5",
                        "createdAt": "2025-04-15T21:27:12.086Z",
                        "updatedAt": "2025-04-15T21:27:12.086Z",
                        "active": true,
                        "email": "usuáriodetestes@gmail.com",
                        "emailNotification": true,
                        "agree": true,
                        "name": "José",
                        "lastName": "Augustho",
                        "passwd": "*************************************",
                        "phone": "(34) 99171-8593",
                        "authorizedSessionsId": [
                          "67feca9e34e83ead55527cc9",
                          "6800351827e549a02865a56a",
                          "68012bbcd25df937ea1f5676"
                        ],
                        "role": "USER"
                      },
                      {
                        "id": "67fecf502cdddf231abdb1e5",
                        "createdAt": "2025-04-15T21:27:12.086Z",
                        "updatedAt": "2025-04-15T21:27:12.086Z",
                        "active": true,
                        "email": "usuáriodetestes1@gmail.com",
                        "emailNotification": true,
                        "agree": true,
                        "name": "José",
                        "lastName": "Augustho",
                        "passwd": "*************************************",
                        "phone": "(34) 99171-8593",
                        "authorizedSessionsId": [
                          "67feca2e34e81ead55527cc9",
                          "6800351527e369a02865a56a",
                          "68012bbcd352f937ea1f5676"
                        ],
                        "role": "USER"
                      },
                      {
                        "id": "67fecf592cdddf231abdb1e5",
                        "createdAt": "2025-04-15T21:27:12.086Z",
                        "updatedAt": "2025-04-15T21:27:12.086Z",
                        "active": true,
                        "email": "usuáriodeteste@gmail.com",
                        "emailNotification": true,
                        "agree": true,
                        "name": "José",
                        "lastName": "Augustho",
                        "passwd": "*************************************",
                        "phone": "(34) 99171-8593",
                        "authorizedSessionsId": [
                          "67feca2e34e83ead65527cc9",
                          "6800351526e549a02865a56a",
                          "68012bbcd252f937ea1f5656"
                        ],
                        "role": "USER"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError | TokenError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/support/users/count": {
      "get": {
        "summary": "Retorna a contagem de todos os usuários. (Somente admins)",
        "tags": ["Support", "User"],
        "description": "Retorna todos os usuários com base na paginação e filtros de busca.",
        "parameters": [
          {
            "name": "search",
            "description": "Pesquisa os usuários que incluirem o parametro search. (Não é case sensitive)",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "example": "José"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Contagem de usuários encontrados",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "count": 3
                      }
                    }
                  },
                  "example": {
                    "status": "Ok",
                    "message": "Usuários encontrados.",
                    "data": {
                      "count": 3
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "AuthError | TokenError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parametros inválidos.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "UserError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          },
          "502": {
            "description": "Erro interno.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "InternalServerError"
                    },
                    "message": {
                      "type": "string",
                      "example": "<Descrição do erro>"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/logout-session": {
      "put": {
        "summary": "Desativar sessão com base em um id.",
        "tags": ["Session"],
        "description": "Desativa a sessão de um usuário com base no sessionId. (Requer que a sessão seja do usuário autenticado ou que o usuário autenticado tenha privilégios de suporte ou administrador)",
        "security": [
          {
            "FingerprintID": []
          },
          {
            "Language": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SessionId"
              },
              "examples": {
                "Desativando uma sessão": {
                  "value": {
                    "sessionId": "67e1d85201acae1a746a3a6b"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "format": "email",
                      "example": "Ok"
                    },
                    "message": {
                      "type": "string",
                      "example": "Usuário autenticado com sucesso."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Não autorizado."
          },
          "400": {
            "description": "Parametros inválidos."
          },
          "502": {
            "description": "Erro interno."
          }
        }
      },
      "get": {
        "summary": "Desativar sessão autenticada.",
        "tags": ["Session"],
        "description": "Desativa a sessão que está autenticada.",
        "requestBody": {
          "required": false
        },
        "responses": {
          "200": {
            "description": "Ok"
          },
          "401": {
            "description": "Não autorizado."
          },
          "400": {
            "description": "Parametros inválidos."
          },
          "502": {
            "description": "Erro interno."
          }
        }
      }
    },
    "/logout-session/all": {
      "get": {
        "summary": "Desativar todas as sessões menos a que está autenticada.",
        "tags": ["Session"],
        "description": "Desativa todas as sessões do usuário, menos a que está autenticada pelo token.",
        "requestBody": {
          "required": false
        },
        "responses": {
          "200": {
            "description": "Ok",
            "properties": {
              "message": {
                "type": "string",
                "example": "Todas as sessões foram desativadas com sucesso."
              }
            }
          },
          "401": {
            "description": "Não autorizado."
          },
          "400": {
            "description": "Parametros inválidos."
          },
          "502": {
            "description": "Erro interno."
          }
        }
      }
    },
    "/unauthorize-session": {
      "put": {
        "summary": "Bloquear sessão.",
        "tags": ["Session"],
        "description": "É usado como medida de segurança para bloquear sessões suspeitas e impedir que dispositivos vinculados à ela façam login. (Requer que a sessão seja do usuário autenticado ou que o usuário autenticado tenha privilégios de suporte ou administrador)",
        "security": [
          {
            "FingerprintID": []
          },
          {
            "Language": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SessionId"
              },
              "examples": {
                "refreshToken": {
                  "value": {
                    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjEyNmYwMzFlYjU3NjIzYmZkOTZlYiIsInNlc3Npb25JZCI6IjY3ZjEyY2QwM2FjNmNiYzU3OTczNzA3MSIsImlhdCI6MTc0Mzg1ODg5NiwiZXhwIjoxOTE2NjU4ODk2fQ.YRDejsPts2C68zr7xXa_TRsmliDoztKeUGu6DwwCXsQ"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok"
          },
          "401": {
            "description": "Não autorizado."
          },
          "400": {
            "description": "Parametros inválidos."
          },
          "502": {
            "description": "Erro interno."
          }
        }
      }
    },
    "/email-exists": {
      "post": {
        "summary": "Verifica se um email está disponível.",
        "tags": ["User"],
        "description": "Ele retorna",
        "security": [
          {
            "FingerprintID": []
          },
          {
            "Language": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Email"
              },
              "examples": {
                "login": {
                  "value": {
                    "email": "usuariodeteste@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Ok"
          },
          "401": {
            "description": "Não autorizado."
          },
          "400": {
            "description": "Parametros inválidos."
          },
          "502": {
            "description": "Erro interno."
          }
        }
      }
    }
  }
}
